# Generated by Django 5.1.7 on 2025-03-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('face_condition', models.TextField()),
                ('medications_taken', models.TextField()),
                ('home_care_items', models.TextField()),
                ('status', models.CharField(choices=[('treated', 'Davolanib bo‘lgan'), ('under_treatment', 'Davolanmoqda'), ('not_arrived', 'Kelmagan')], default='under_treatment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='monitoring.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.region'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='monitoring.typedisease'),
        ),
    ]
