# Generated by Django 5.1.7 on 2025-03-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='total_payment_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('treated', 'Davolanib bo‘lgan'), ('debtor', 'Qarzdor'), ('paid', 'tolangan'), ('not_arrived', 'Kelmagan')], default='under_treatment', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='monitoring.patient')),
            ],
        ),
    ]
