# Generated by Django 5.1.7 on 2025-03-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_patient_total_payment_due_alter_patient_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpayment',
            name='description',
        ),
    ]
