# Generated by Django 5.1.7 on 2025-03-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_patientpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('treated', 'Davolanib bo‘lgan'), ('debtor', 'Qarzdor'), ('paid', 'tolangan'), ('not_arrived', 'Kelmagan')], default='debtor', max_length=20),
        ),
    ]
