# Generated by Django 5.1.7 on 2025-04-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_patient_address_alter_patient_face_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='monitoring.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.region'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='monitoring.typedisease'),
        ),
        migrations.AlterField(
            model_name='patientpayment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='monitoring.patient'),
        ),
    ]
