# Generated by Django 5.1.7 on 2025-04-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_patient_is_deleted_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='total_payment_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
